export const frenchPrompts = [
  "Un coucher de soleil sur une chaîne de montagnes",
  "Une vue panoramique de ville la nuit",
  "Une plage tropicale avec des palmiers",
  "Un paysage d'hiver enneigé",
  "Un jardin avec des fleurs colorées",
  "Un gratte-ciel futuriste",
  "Un château sur une colline",
  "Une chute d'eau dans une forêt",
  "Un ballon à air chaud dans le ciel",
  "Un désert avec des dunes de sable",
  "Un phare sur une falaise",
  "Un carnaval avec des lumières et des manèges",
  "Un groupe de pingouins sur un iceberg",
  "Une station spatiale en orbite autour de la Terre",
  "Un groupe de lions dans la savane",
  "Un champ de tournesols",
  "Une chute d'eau dans une grotte",
  "Un château dans les nuages",
  "Un fusée décollant dans l'espace",
  "Un hôtel de plage avec parasols et chaises",
  "Un stade de football pendant un match",
  "Un dragon crachant le feu",
  "Une cabane enneigée dans les bois",
  "Un festival de ballons à air chaud",
  "Un château avec un fossé et un pont-levis",
  "Une chute d'eau dans une jungle",
  "Un robot géant dans une ville",
  "Un arc-en-ciel sur une plage",
  "Un train traversant des montagnes",
  "Un ballon à air chaud au coucher du soleil",
  "Un château avec une vue panoramique",
  "Une chute d'eau derrière un arc-en-ciel",
  "Un château au milieu d'un lac",
  "Un match de football sous une forte pluie",
  "Un château avec un escalier en spirale",
  "Un ballon à air chaud dans un ciel orageux",
  "Un château avec un jardin secret",
  "Une chute d'eau dans un canyon",
  "Un château avec un pont-levis et un fossé",
  "Un ballon à air chaud le matin",
  "Un château avec une tour en spirale",
  "Une chute d'eau dans une vallée",
  "Un château avec une terrasse sur le toit",
  "Un ballon à air chaud sur l'océan",
  "Un château avec une chambre cachée",
  "Une chute d'eau dans un vallon de forêt",
  "Un château avec un pont-levis et des tours",
  "Un ballon à air chaud avec un arc-en-ciel",
  "Un château avec une entrée imposante",
  "Une chute d'eau dans une grotte",
  "Une ville futuriste avec des gratte-ciel cyberpunk",
  "Un homme cyberpunk marchant dans une rue sombre",
  "Une voiture volante dans un ciel futuriste",
  "Un bar cyberpunk rempli de personnages étranges",
  "Une fille cyberpunk avec des implants cybernétiques",
  "Un groupe de motards cyberpunk sur une autoroute futuriste",
  "Un parc d'attractions futuriste avec des attractions high-tech",
  "Un héros cyberpunk combattant des robots dans une ville futuriste",
  "Un night-club cyberpunk avec de la musique techno",
  "Un bâtiment gouvernemental futuriste avec des caméras de surveillance",  "Un vaisseau spatial cyberpunk en vol",
  "Un membre de la police cyberpunk patrouillant dans une ville futuriste",
  "Un personnage cyberpunk utilisant un ordinateur haute technologie",
  "Un gratte-ciel futuriste avec des panneaux publicitaires lumineux",
  "Un personnage cyberpunk dans un monde virtuel",
  "Un parc d'attractions cyberpunk avec des montagnes russes high-tech",
  "Un hôtel futuriste avec des chambres high-tech",
  "Un personnage cyberpunk avec des armes futuristes",
  "Un centre commercial futuriste avec des magasins high-tech",
  "Un parc d'attractions cyberpunk avec des manèges futuristes",
  "Une course de voitures futuristes dans une ville cyberpunk",
  "Un personnage cyberpunk dans un film de science-fiction",
  "Un train futuriste voyageant à travers une ville cyberpunk"
];
export const styles = {
  flex_box_col: "flex items-center justify-center flex-col p-5",
  flex_box_col_start: "flex items-start justify-center flex-col p-5",
  flex_box_row: "flex items-center",
  text_header: "text-blue-500 font-semibold md:text-[32px] text-[18px]",
  text_body: " font-poppins md:text-[18px] text-[16px] font-normal",
};
// Red F54646
export const navlinks = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "create",
    title: "Create post",
  },
  {
    id: "explore",
    title: "Explore",
  },

  {
    id: "about",
    title: "About",
  },
];
export const englishPrompts = [
  "A sunset over a mountain range",
  "A panoramic view of the city at night",
  "A tropical beach with palm trees",
  "A snowy winter landscape",
  "A garden with colorful flowers",
  "A futuristic skyscraper",
  "A castle on a hill",
  "A waterfall in a forest",
  "A hot air balloon in the sky",
  "A desert with sand dunes",
  "A lighthouse on a cliff",
  "A carnival with lights and rides",
  "A group of penguins on an iceberg",
  "A space station orbiting the Earth",
  "A group of lions in the savannah",
  "A field of sunflowers",
  "A waterfall in a cave",
  "A castle in the clouds",
  "A rocket launching into space",
  "A beach hotel with umbrellas and chairs",
  "A football stadium during a game",
  "A dragon breathing fire",
  "A snow cabin in the woods",
  "A hot air balloon festival",
  "A castle with a moat and a drawbridge",
  "A waterfall in a jungle",
  "A giant robot in a city",
  "A rainbow on a beach",
  "A train crossing mountains",
  "A hot air balloon at sunset",
  "A castle with a panoramic view",
  "A waterfall behind a rainbow",
  "A castle in the middle of a lake",
  "A football game in heavy rain",
  "A castle with a spiral staircase",
  "A hot air balloon in a stormy sky",
  "A castle with a secret garden",
  "A waterfall in a canyon",
  "A castle with a drawbridge and a moat",
  "A hot air balloon in the morning",
  "A castle with a spiral tower",
  "A waterfall in a valley",
  "A castle with a rooftop terrace",
  "A hot air balloon over the ocean",
  "A castle with a hidden room",
  "A waterfall in a forest glen",
  "A castle with a drawbridge and towers",
  "A hot air balloon with a rainbow",
  "A castle with an imposing entrance",
  "A waterfall in a cave",
  "A futuristic city with cyberpunk skyscrapers",
  "A cyberpunk man walking down a dark street",
  "A flying car in a futuristic sky",
  "A cyberpunk bar filled with strange characters",
  "A cyberpunk girl with cybernetic implants",
  "A group of cyberpunk bikers on a futuristic highway",
  "A futuristic theme park with high-tech attractions",
  "A cyberpunk hero fighting robots in a futuristic city",
  "A cyberpunk nightclub with techno music",
  "A futuristic government building with surveillance cameras",
  "A cyberpunk spaceship in flight",
  "A cyberpunk police officer patrolling a futuristic city",
  "A cyberpunk character using high-tech computer"]